site_name: My GitHub Site
site_url: https://maroph.github.io/
site_description: My GitHub user site
site_author: Manfred Rosenboom (maroph)

theme:
    name: mkdocs

nav:
    - Home: index.md
    - Info:
        - About: info/index.md
        - License: info/license.md

docs_dir: docs-src
site_dir: docs

copyright: (c) 2020 Manfred Rosenboom (maroph)

